# https://docs.github.com/en/code-security/dependabot
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daily"