source "https://rubygems.org"

# Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# To upgrade, run `bundle update github-pages`.

gem "rake"
gem "tzinfo-data"
gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
    gem "jemoji"
    gem "jekyll-asciidoc"
    gem "github-pages"
    gem "jekyll-paginate"
    gem "jekyll-sitemap"
    gem "jekyll-gist"
    gem "jekyll-feed"
    gem "jekyll-include-cache"
    gem "jekyll-algolia"
    gem "jekyll-archives"
end
