name: "The Echoes Codacy Security Scan"
run-name: "Codacy Security Scan on Echoes - [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"
# https://app.codacy.com/organizations/gh/Gervi-Hera-Vitr/dashboard

on:
  push:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '47 20 * * 5'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true


jobs:

  codacy-security-scan-with-codacy:
    timeout-minutes: 17
    runs-on: self-hosted
    name: "Codacy Security Scan with Publishing on the Echoes"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: codacy

    steps:

      - name: "Checkout the Echoes repository source code"
        uses: actions/checkout@3b9b8c884f6b4bb4d5be2779c26374abadae0871
        timeout-minutes: 1

      - name: "Run Codacy Analysis CLI Action on the Echoes repository and generate SARIF report"
        uses: codacy/codacy-analysis-cli-action@09916000460adeeedc96b9704f86deba53e2ad5d
        timeout-minutes: 14
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 1999


      - name: "Upload Echoes SARIF results to CodeQL Services"
        uses: github/codeql-action/upload-sarif@a1695c562bbfa68dc5ab58c9b5e9f616b52bf5be
        timeout-minutes: 4
        with:
          sarif_file: results.sarif
