# rdd13r on 2024-08-12
name: "Lugaru Build Sanity Checks on each Push"
run-name: "Build Host Environment on each Push by ${{ github.actor }} with ${{ github.event_name }}"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  discussions: write
  issues: write
  pull-requests: write
  actions: read
  statuses: read

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  build-echoes-on-every-push:
    timeout-minutes: 5
    runs-on: self-hosted
    name: "Build Echoes for sanity checks on every push"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gradle

    steps:

      - name: "Checkout the Echoes repository source code at root"
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        timeout-minutes: 1

      - name: "Build the Echoes using indigenous gradle, with gradle wrapper handover if present"
        timeout-minutes: 2
        run: gradle build --scan

      - name: "Generate and submit Gradle dependency graph"
        uses: gradle/actions/dependency-submission@c94eb9d32c39fe014e838aa5efdcc186a8ba7e53