name: "Build and Deploy the Echoes Jekyll Site with GitHub Pages"
run-name: "Jekyll Build and Deploy: ${{ github.actor }} with ${{ github.event_name }}"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:

  build-echoes-jekyll-site:
    timeout-minutes: 5
    runs-on: self-hosted
    name: "Build Jekyll Site from the project root"

    env:
      BUNDLE_PATH: vendor/bundle

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: jekyll

    steps:
      - name: "Checkout the Echoes repository source code"
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        timeout-minutes: 1

      - name: "Install necessary `ruby` `gem` dependencies"
        timeout-minutes: 3
        run: |
          cd docs
          bundle install

      - name: "Build the Echoes Jekyll site"
        timeout-minutes: 3
        run: |
          cd docs
          bundle exec jekyll build -d ../_site

      - name: "Package and Upload Project Site built Artifact"
        uses: actions/upload-pages-artifact@2d163be3ddce01512f3eea7ac5b7023b5d643ce1
        timeout-minutes: 2
        with:
          path: ./_site


  deploy-echoes-jekyll-site-to-github-pages:
    timeout-minutes: 3
    runs-on: self-hosted
    needs: build-echoes-jekyll-site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: github-pages

    steps:
      - name: "Deploy uploaded Echoes Artifact to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@854d7aa1b99e4509c4d1b53d69b7ba4eaf39215a
