name: "Label the Echoes Pull Request"
run-name: "Label Pull Request with IAW Labeling Guidelines examining content by ${{ github.actor }} with ${{ github.event_name }}"

on:
  pull_request_target:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  label-pull-request-iaw-labeling-guidelines:
    timeout-minutes: 1
    runs-on: self-hosted
    name: "Label Echoes Pull Request with IAW Labeling Guidelines examining content"

    permissions:
      contents: read
      pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: iaw

    steps:
      - name: "Label Echoes Pull Request pushing labels to GitHub Pull Request"
        uses: actions/labeler@3629d5568b59204f18786372f6d740d649719488
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
