name: "Manage Stale Issues and Pull Requests on the Echoes of Wasteland"
run-name: "the Echoes - Manage Stale Issues and Pull Requests on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  stale-echoes-issues-and-pull-requests-check:
    timeout-minutes: 2
    runs-on: self-hosted
    name: "Manage Stale Issues and Pull Requests on Echoes"
    
    strategy:
      fail-fast: true

    steps:
      - name: "Run Stale Issues and Pull Requests checks in the Echoes repository [${{ github.repository }}] by ${{ github.actor }}"
        uses: actions/stale@f69122271d990fd11f5594ccff2296f00ff59b49
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 21
          days-before-close: 13

          days-before-issue-stale: 28
          stale-issue-label: issue-has-no-activity
          stale-issue-message: |
            Closing `stale` issue as irrelevant: 
            This issue is dormant with no activity. 
            If this issue is still relevant,
            please follow the [contributing guide](https://github.com/Gervi-Hera-Vitr/Gervi-Hera-Vitr/blob/main/CONTRIBUTING.md) to:
            - upgrade and reopen, or
            - open a new issue instead.

          days-before-issue-close: 11
          close-issue-label: 'stale-issue-closed'
          close-issue-message: |
            This issue was closed because it has been _dormant_ with no activity.

          days-before-pr-stale: 17
          stale-pr-label: 'pr-has-no-activity'
          stale-pr-message: |
            Stale pull request: Closing abandoned pull request as irrelevant.
            If this pull request is still relevant, please upgrade and reopen.

          days-before-pr-close: 9
          close-pr-label: 'stale-pr-closed'
          close-pr-message: |
            This PR was closed because it has been stalled with no activity.
